<a href="https://colab.research.google.com/github/sucheerarighthere/bsc_dpdm22/blob/main/Performace_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Performace Evaluation คือการวัดผล

In [4]:
from sklearn import datasets
iris_data = datasets.load_iris()

In [5]:
x = iris_data['data']
y= iris_data['target']

### generate code for training decisin tree and evaluate with 10-fold cross validation

In [6]:

from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

# Load the Iris dataset
iris = load_iris()

# Split the dataset into features (X) and target (y)
X = iris.data
y = iris.target

# Create an instance of the DecisionTreeClassifier class
clf = DecisionTreeClassifier()

# Perform 10-fold cross-validation and compute the mean accuracy
scores = cross_val_score(clf, X, y, cv=10)
mean_accuracy = scores.mean()

# Print the mean accuracy
print("Mean accuracy:", mean_accuracy)

Mean accuracy: 0.96

In [7]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

# Load the Iris dataset
iris = load_iris()

# Split the dataset into features (X) and target (y)
X = iris.data
y = iris.target

# Create an instance of the DecisionTreeClassifier class
clf = DecisionTreeClassifier(max_depth=2)

# Perform 10-fold cross-validation and compute the mean accuracy
scores = cross_val_score(clf, X, y, cv=10)
mean_accuracy = scores.mean()

# Print the mean accuracy
print("Mean accuracy:", mean_accuracy)

Mean accuracy: 0.9466666666666667

อันนี้มีการสรุป std

In [8]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut, cross_val_score

# Load the iris dataset
iris = load_iris()

# Split the data into features (X) and labels (y)
X = iris.data
y = iris.target

# Create an instance of the decision tree classifier
clf = DecisionTreeClassifier()

# Create a leave-one-out cross-validation object
loo = LeaveOneOut()

# Evaluate the decision tree classifier using leave-one-out cross-validation
scores = cross_val_score(clf, X, y, cv=loo)

# Compute the mean accuracy and standard deviation and print them out
mean_accuracy = scores.mean()
std_dev = scores.std()
print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_dev)

Mean accuracy: 0.9466666666666667
Standard deviation: 0.2246973272847029

In [9]:
from sklearn.datasets import load_iris
from sklearn.model_selection import LeaveOneOut, cross_val_score
from sklearn.tree import DecisionTreeClassifier

# Load the Iris dataset
iris = load_iris()

# Split the dataset into features (X) and target (y)
X = iris.data
y = iris.target

# Create an instance of the DecisionTreeClassifier class
clf = DecisionTreeClassifier()

# Create an instance of the LeaveOneOut class
loo = LeaveOneOut()

# Perform leave-one-out cross-validation and compute the mean accuracy
scores = cross_val_score(clf, X, y, cv=loo)
mean_accuracy = scores.mean()

# Print the mean accuracy
print("Mean accuracy:", mean_accuracy)

Mean accuracy: 0.9466666666666667

# วิธียาก

transform numpy to data frame with column name

In [10]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [11]:
import pandas as pd

In [12]:
columns=iris_data['feature_names']
x_df = pd.DataFrame(X,columns=columns)

In [13]:
x_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

### ขั้นตอนแบ่งfold >> shuffle ข้อมูล

In [14]:
x_df['label']=y #เพิ่มคอลัมน์ก่อน ค่อยชัฟเฟิล
x_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [15]:
shuffle = x_df.sample(frac=1)
shuffle
#แต่การสลับindex ต้องสลับ คำตอบด้วย
#มี column ที่บอกข้อมูลแล้ว เราสามารถ

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
31,5.4,3.4,1.5,0.4,0
120,6.9,3.2,5.7,2.3,2
47,4.6,3.2,1.4,0.2,0
25,5.0,3.0,1.6,0.2,0
75,6.6,3.0,4.4,1.4,1
...,...,...,...,...,...
16,5.4,3.9,1.3,0.4,0
123,6.3,2.7,4.9,1.8,2
63,6.1,2.9,4.7,1.4,1
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [16]:
shuffle['fold']=15*[1,2,3,4,5,6,7,8,9,10]
shuffle

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
31,5.4,3.4,1.5,0.4,0,1
120,6.9,3.2,5.7,2.3,2,2
47,4.6,3.2,1.4,0.2,0,3
25,5.0,3.0,1.6,0.2,0,4
75,6.6,3.0,4.4,1.4,1,5
...,...,...,...,...,...,...
16,5.4,3.9,1.3,0.4,0,6
123,6.3,2.7,4.9,1.8,2,7
63,6.1,2.9,4.7,1.4,1,8
3,4.6,3.1,1.5,0.2,0,9
4,5.0,3.6,1.4,0.2,0,10

HW -10 fold รอบที่1 อันแรก test ที่เหลือ train วัดผลด้วยdata คาบที่แล้ว

In [17]:
shuffle.sort_values('fold')

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
31,5.4,3.4,1.5,0.4,0,1
61,5.9,3.0,4.2,1.5,1,1
101,5.8,2.7,5.1,1.9,2,1
128,6.4,2.8,5.6,2.1,2,1
136,6.3,3.4,5.6,2.4,2,1
...,...,...,...,...,...,...
84,5.4,3.0,4.5,1.5,1,10
88,5.6,3.0,4.1,1.3,1,10
142,5.8,2.7,5.1,1.9,2,10
51,6.4,3.2,4.5,1.5,1,10
4,5.0,3.6,1.4,0.2,0,10

In [18]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [19]:
## Define feature names
feature_names = iris_data.feature_names

# Define target names
target_names = iris_data.target_names

# Define Decision Tree Classifier
clf = DecisionTreeClassifier()

# Define KFold with 10 folds
kf = KFold(n_splits=10, shuffle=True, random_state=6)

# Initialize lists to store results
accuracies = []
feature_importances = []

# Loop through each fold
for fold, (train_index, test_index) in enumerate(kf.split(iris_data.data)):
    
    # Get train and test data
    X_train, X_test = iris_data.data[train_index], iris_data.data[test_index]
    y_train, y_test = iris_data.target[train_index], iris_data.target[test_index]
    
    # Fit classifier on training data
    clf.fit(X_train, y_train)
    
    # Make predictions on test data
    y_pred = clf.predict(X_test)
    
    # Calculate accuracy score
    accuracy = accuracy_score(y_test, y_pred)
    
    # Store accuracy score in list
    accuracies.append(accuracy)
    
    # Get feature importances
    feature_importance = clf.feature_importances_
    
    # Store feature importances in list
    feature_importances.append(feature_importance)

    # Create a DataFrame to display the iris data for each fold
    iris_data1 = np.concatenate((X_test, y_test.reshape(-1,1)), axis=1)
    columns = iris_data['feature_names']
    X_df = pd.DataFrame(data=iris_data1, columns=columns+['label'])
    X_df['label'] = y_test
    df = X_df.sample(frac=1, random_state=6)
    df['fold'] = fold+1

    # Print fold number and accuracy score
    print(f"Fold {fold+1}")
    print("Cross-validation accuracy: %0.2f (+/- %0.2f)" % (np.mean(accuracies), np.std(accuracies) * 2))
    
    # Show sample of data for current fold
    print(df)
    
    print("\n")

Fold 1
Cross-validation accuracy: 1.00 (+/- 0.00)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                6.1               3.0                4.9               1.8
13                7.7               3.0                6.1               2.3
6                 5.5               2.4                3.7               1.0
7                 5.7               2.9                4.2               1.3
2                 5.1               3.3                1.7               0.5
8                 6.4               3.2                5.3               2.3
5                 6.4               2.9                4.3               1.3
12                6.1               2.6                5.6               1.4
1                 5.0               3.6                1.4               0.2
0                 4.7               3.2                1.3               0.2
14                6.4               3.1                5.5               1.8
4                 5.5               2.3                4.0               1.3
3                 5.1               3.4                1.5               0.2
9                 6.5               3.0                5.5               1.8
10                6.3               2.7                4.9               1.8

    label  fold
11      2     1
13      2     1
6       1     1
7       1     1
2       0     1
8       2     1
5       1     1
12      2     1
1       0     1
0       0     1
14      2     1
4       1     1
3       0     1
9       2     1
10      2     1


Fold 2
Cross-validation accuracy: 0.97 (+/- 0.07)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                7.1               3.0                5.9               2.1
13                6.0               2.2                5.0               1.5
6                 5.7               2.8                4.5               1.3
7                 6.3               2.5                4.9               1.5
2                 5.2               4.1                1.5               0.1
8                 6.3               2.3                4.4               1.3
5                 6.4               3.2                4.5               1.5
12                7.6               3.0                6.6               2.1
1                 4.8               3.1                1.6               0.2
0                 5.1               3.5                1.4               0.2
14                6.9               3.2                5.7               2.3
4                 5.1               3.8                1.9               0.4
3                 4.9               3.6                1.4               0.1
9                 5.8               2.6                4.0               1.2
10                5.0               2.3                3.3               1.0

    label  fold
11      2     2
13      2     2
6       1     2
7       1     2
2       0     2
8       1     2
5       1     2
12      2     2
1       0     2
0       0     2
14      2     2
4       0     2
3       0     2
9       1     2
10      1     2


Fold 3
Cross-validation accuracy: 0.96 (+/- 0.06)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                6.3               2.9                5.6               1.8
13                6.3               2.8                5.1               1.5
6                 5.2               2.7                3.9               1.4
7                 5.9               3.0                4.2               1.5
2                 5.1               3.5                1.4               0.3
8                 5.6               2.9                3.6               1.3
5                 5.0               3.3                1.4               0.2
12                6.4               2.8                5.6               2.1
1                 5.4               3.9                1.3               0.4
0                 4.3               3.0                1.1               0.1
14                6.3               2.5                5.0               1.9
4                 5.1               3.8                1.6               0.2
3                 4.8               3.0                1.4               0.3
9                 6.1               2.8                4.0               1.3
10                5.7               3.0                4.2               1.2

    label  fold
11      2     3
13      2     3
6       1     3
7       1     3
2       0     3
8       1     3
5       0     3
12      2     3
1       0     3
0       0     3
14      2     3
4       0     3
3       0     3
9       1     3
10      1     3


Fold 4
Cross-validation accuracy: 0.97 (+/- 0.07)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                6.4               2.7                5.3               1.9
13                7.7               2.6                6.9               2.3
6                 4.4               3.0                1.3               0.2
7                 6.9               3.1                4.9               1.5
2                 5.7               3.8                1.7               0.3
8                 6.5               2.8                4.6               1.5
5                 4.9               3.1                1.5               0.2
12                7.7               3.8                6.7               2.2
1                 4.8               3.0                1.4               0.1
0                 4.6               3.4                1.4               0.3
14                5.6               2.8                4.9               2.0
4                 5.2               3.5                1.5               0.2
3                 5.4               3.4                1.7               0.2
9                 6.6               2.9                4.6               1.3
10                6.7               2.5                5.8               1.8

    label  fold
11      2     4
13      2     4
6       0     4
7       1     4
2       0     4
8       1     4
5       0     4
12      2     4
1       0     4
0       0     4
14      2     4
4       0     4
3       0     4
9       1     4
10      2     4


Fold 5
Cross-validation accuracy: 0.96 (+/- 0.07)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                5.8               2.7                5.1               1.9
13                5.8               2.7                5.1               1.9
6                 5.6               3.0                4.1               1.3
7                 5.5               2.5                4.0               1.3
2                 4.7               3.2                1.6               0.2
8                 5.6               2.7                4.2               1.3
5                 5.4               3.0                4.5               1.5
12                6.4               2.8                5.6               2.2
1                 5.8               4.0                1.2               0.2
0                 4.6               3.1                1.5               0.2
14                6.5               3.0                5.2               2.0
4                 6.0               2.7                5.1               1.6
3                 5.0               2.0                3.5               1.0
9                 5.7               2.8                4.1               1.3
10                6.3               3.3                6.0               2.5

    label  fold
11      2     5
13      2     5
6       1     5
7       1     5
2       0     5
8       1     5
5       1     5
12      2     5
1       0     5
0       0     5
14      2     5
4       1     5
3       1     5
9       1     5
10      2     5


Fold 6
Cross-validation accuracy: 0.96 (+/- 0.06)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                7.2               3.0                5.8               1.6
13                6.3               3.4                5.6               2.4
6                 6.2               2.9                4.3               1.3
7                 5.1               2.5                3.0               1.1
2                 4.6               3.2                1.4               0.2
8                 6.5               3.0                5.8               2.2
5                 6.1               3.0                4.6               1.4
12                7.9               3.8                6.4               2.0
1                 5.1               3.7                1.5               0.4
0                 4.9               3.1                1.5               0.1
14                6.9               3.1                5.4               2.1
4                 6.1               2.8                4.7               1.2
3                 6.7               3.1                4.4               1.4
9                 6.8               3.0                5.5               2.1
10                5.7               2.5                5.0               2.0

    label  fold
11      2     6
13      2     6
6       1     6
7       1     6
2       0     6
8       2     6
5       1     6
12      2     6
1       0     6
0       0     6
14      2     6
4       1     6
3       1     6
9       2     6
10      2     6


Fold 7
Cross-validation accuracy: 0.96 (+/- 0.07)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                5.8               2.7                3.9               1.2
13                6.7               3.1                5.6               2.4
6                 4.5               2.3                1.3               0.3
7                 4.4               3.2                1.3               0.2
2                 4.8               3.4                1.9               0.2
8                 5.3               3.7                1.5               0.2
5                 5.5               3.5                1.3               0.2
12                7.3               2.9                6.3               1.8
1                 4.6               3.6                1.0               0.2
0                 5.0               3.4                1.5               0.2
14                6.9               3.1                5.1               2.3
4                 5.0               3.2                1.2               0.2
3                 5.5               4.2                1.4               0.2
9                 6.3               3.3                4.7               1.6
10                6.8               2.8                4.8               1.4

    label  fold
11      1     7
13      2     7
6       0     7
7       0     7
2       0     7
8       0     7
5       0     7
12      2     7
1       0     7
0       0     7
14      2     7
4       0     7
3       0     7
9       1     7
10      1     7


Fold 8
Cross-validation accuracy: 0.96 (+/- 0.06)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                7.7               2.8                6.7               2.0
13                6.7               3.0                5.2               2.3
6                 5.8               2.7                4.1               1.0
7                 5.6               2.5                3.9               1.1
2                 4.8               3.4                1.6               0.2
8                 5.9               3.2                4.8               1.8
5                 4.9               2.4                3.3               1.0
12                6.7               3.3                5.7               2.1
1                 5.4               3.7                1.5               0.2
0                 5.4               3.9                1.7               0.4
14                5.9               3.0                5.1               1.8
4                 7.0               3.2                4.7               1.4
3                 5.0               3.5                1.3               0.3
9                 6.0               2.9                4.5               1.5
10                5.5               2.6                4.4               1.2

    label  fold
11      2     8
13      2     8
6       1     8
7       1     8
2       0     8
8       1     8
5       1     8
12      2     8
1       0     8
0       0     8
14      2     8
4       1     8
3       0     8
9       1     8
10      1     8


Fold 9
Cross-validation accuracy: 0.96 (+/- 0.07)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                6.2               2.8                4.8               1.8
13                6.8               3.2                5.9               2.3
6                 5.6               3.0                4.5               1.5
7                 6.0               3.4                4.5               1.6
2                 5.2               3.4                1.4               0.2
8                 6.7               3.1                4.7               1.5
5                 6.1               2.9                4.7               1.4
12                7.4               2.8                6.1               1.9
1                 5.1               3.8                1.5               0.3
0                 5.7               4.4                1.5               0.4
14                6.7               3.3                5.7               2.5
4                 5.0               3.5                1.6               0.6
3                 5.4               3.4                1.5               0.4
9                 5.8               2.8                5.1               2.4
10                7.2               3.2                6.0               1.8

    label  fold
11      2     9
13      2     9
6       1     9
7       1     9
2       0     9
8       1     9
5       1     9
12      2     9
1       0     9
0       0     9
14      2     9
4       0     9
3       0     9
9       2     9
10      2     9


Fold 10
Cross-validation accuracy: 0.96 (+/- 0.07)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                7.2               3.6                6.1               2.5
13                6.0               3.0                4.8               1.8
6                 6.6               3.0                4.4               1.4
7                 6.7               3.0                5.0               1.7
2                 5.0               3.0                1.6               0.2
8                 5.7               2.6                3.5               1.0
5                 6.2               2.2                4.5               1.5
12                6.5               3.2                5.1               2.0
1                 4.4               2.9                1.4               0.2
0                 4.9               3.0                1.4               0.2
14                6.2               3.4                5.4               2.3
4                 6.0               2.2                4.0               1.0
3                 5.0               3.4                1.6               0.4
9                 5.5               2.4                3.8               1.1
10                4.9               2.5                4.5               1.7

    label  fold
11      2    10
13      2    10
6       1    10
7       1    10
2       0    10
8       1    10
5       1    10
12      2    10
1       0    10
0       0    10
14      2    10
4       1    10
3       0    10
9       1    10
10      2    10

# 24 feb 2023

In [21]:
#with confusiopn matrix
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, cross_val_predict
from sklearn.metrics import confusion_matrix
import numpy as np

# Load iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create decision tree classifier
dtc = DecisionTreeClassifier()

# Perform 10-fold cross-validation on the training set
y_pred = cross_val_predict(dtc, X_train, y_train, cv=10)

# Fit the classifier on the training set
dtc.fit(X_train, y_train)

# Predict the labels of the test set
y_pred_test = dtc.predict(X_test)

# Generate confusion matrix for the test set
cm = confusion_matrix(y_test, y_pred_test)

# Generate confusion matrix for the training set
cm_train = confusion_matrix(y_train, y_pred)

# Print results
print("Confusion matrix for training set:")
print(cm_train)
print("Confusion matrix for test set:")
print(cm)

Confusion matrix for training set:
[[31  0  0]
 [ 0 33  4]
 [ 0  3 34]]
Confusion matrix for test set:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

# key from al.tohn

In [22]:
shuffle

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
31,5.4,3.4,1.5,0.4,0,1
120,6.9,3.2,5.7,2.3,2,2
47,4.6,3.2,1.4,0.2,0,3
25,5.0,3.0,1.6,0.2,0,4
75,6.6,3.0,4.4,1.4,1,5
...,...,...,...,...,...,...
16,5.4,3.9,1.3,0.4,0,6
123,6.3,2.7,4.9,1.8,2,7
63,6.1,2.9,4.7,1.4,1,8
3,4.6,3.1,1.5,0.2,0,9
4,5.0,3.6,1.4,0.2,0,10

In [56]:
test_fold = 1 #เอาfold 1 มาเป็นtest #พยายามใช้ ชื่อให้ตรง
test_data = shuffle[shuffle['fold']==test_fold] #define test data
training_data = shuffle[shuffle['fold']!=test_fold] #define traning data

In [29]:
test_data #ดูหน้าตา สองคอลัมน์สุดท้ายไม่เอา มันเปนโฟล

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
31,5.4,3.4,1.5,0.4,0,1
96,5.7,2.9,4.2,1.3,1,1
30,4.8,3.1,1.6,0.2,0,1
46,5.1,3.8,1.6,0.2,0,1
143,6.8,3.2,5.9,2.3,2,1
128,6.4,2.8,5.6,2.1,2,1
61,5.9,3.0,4.2,1.5,1,1
39,5.1,3.4,1.5,0.2,0,1
101,5.8,2.7,5.1,1.9,2,1
136,6.3,3.4,5.6,2.4,2,1
42,4.4,3.2,1.3,0.2,0,1
54,6.5,2.8,4.6,1.5,1,1
57,4.9,2.4,3.3,1.0,1,1
8,4.4,2.9,1.4,0.2,0,1
132,6.4,2.8,5.6,2.2,2,1

In [55]:
X_test = test_data.iloc[:,:-2] #เอาทุกอันยกเว้นสองคอลลัมน์สุดท้าย
Y_test =  test_data.iloc[:,-2] #เอาแค่สองคอลสุดท้าย
X_train =training_data.iloc[:,:-2]
Y_train =training_data.iloc[:,-2]

In [63]:
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [53]:
model = DecisionTreeClassifier(max_depth=2) #define
model.fit(X_train,Y_train) #train
y_predict = model.predict(X_test) #predict

In [54]:
acc = accuracy_score(Y_test,y_predict)
print(f'accuracy of fold {test_fold}={acc}')

accuracy of fold 1=1.0

In [65]:
acc_fold=[]
for test_fold in range(1,11):
  test_data = shuffle[shuffle['fold']==test_fold] #define test data
  training_data = shuffle[shuffle['fold']!=test_fold] #define traning data

  X_test = test_data.iloc[:,:-2] #เอาทุกอันยกเว้นสองคอลลัมน์สุดท้าย
  Y_test =  test_data.iloc[:,-2]
  X_train =training_data.iloc[:,:-2]
  Y_train =training_data.iloc[:,-2]

  model = DecisionTreeClassifier(max_depth=2) #define
  model.fit(X_train,Y_train) #train
  y_predict = model.predict(X_test) #predict

  acc = accuracy_score(Y_test,y_predict)
  print(f'accuracy of fold {test_fold}={acc}')
  acc_fold.append(acc)
#ปกติเราไม่ไรด้หยุดแค่นี้ปกติเราก็เอาเลขไปใช้ต่อ อย่าลืมสร้างลิสต์มาเก็บ 
#จบแบบสวยๆ ปริ้นค่าเฉลี่ยด้วย
print (f'\naverage accuracy = {np.mean(acc)}')

accuracy of fold 1=1.0
accuracy of fold 2=0.9333333333333333
accuracy of fold 3=0.9333333333333333
accuracy of fold 4=1.0
accuracy of fold 5=0.8666666666666667
accuracy of fold 6=0.9333333333333333
accuracy of fold 7=0.9333333333333333
accuracy of fold 8=1.0
accuracy of fold 9=0.8
accuracy of fold 10=0.9333333333333333

average accuracy = 0.9333333333333333